package com.hoshino.cti.register;

import com.c2h6s.etshtinker.Modifiers.Armor.*;
import com.c2h6s.etshtinker.Modifiers.*;
import com.hoshino.cti.Modifier.Armor.*;
import com.hoshino.cti.Modifier.*;
import com.hoshino.cti.Modifier.Contributors.*;
import com.hoshino.cti.Modifier.Developer.*;
import com.hoshino.cti.Modifier.Mob.BuriedOcean;
import com.hoshino.cti.Modifier.Replace.*;
import com.hoshino.cti.Modifier.aetherCompact.*;
import com.hoshino.cti.Modifier.iafCompact.*;
import com.hoshino.cti.Modifier.l2Compact.*;
import com.hoshino.cti.Modifier.miscCompact.*;
import com.hoshino.cti.Modifier.slot.*;
import com.hoshino.cti.Cti;
import com.hoshino.cti.Modifier.test;
import com.hoshino.cti.Modifier.underGardenCompact.*;
import slimeknights.tconstruct.library.modifiers.util.ModifierDeferredRegister;
import slimeknights.tconstruct.library.modifiers.util.StaticModifier;

public class CtiModifiers {
    /**
     * 词条的注册部分
     * 图省事所有直接把等号外部分写在一起了（
     */
    public static ModifierDeferredRegister MODIFIERS = ModifierDeferredRegister.create(Cti.MOD_ID);

    public static final StaticModifier<test> TEST_MODIFIER = MODIFIERS.register("test", test::new);

    public static final StaticModifier<ElectricProtect> electric_protect = MODIFIERS.register("electric_protect", ElectricProtect::new);
    public static final StaticModifier<ScorchProtect> scorch_protect = MODIFIERS.register("scorch_protect", ScorchProtect::new);
    public static final StaticModifier<FreezeProtect> freeze_protect = MODIFIERS.register("freeze_protect", FreezeProtect::new);
    public static final StaticModifier<PressureProtect> pressure_protect = MODIFIERS.register("pressure_protect", PressureProtect::new);
    public static final StaticModifier<SpaceSuitModifier> space_suit = MODIFIERS.register("space_suit", SpaceSuitModifier::new);
    public static final StaticModifier<GravityNormalize> gravity_normalizer = MODIFIERS.register("gravity_normalizer", GravityNormalize::new);
    public static final StaticModifier<TimeToJudge> timetojudge = MODIFIERS.register("timetojudge", TimeToJudge::new);
    public static final StaticModifier<NetherFire> netherfire = MODIFIERS.register("netherfire", NetherFire::new);
    public static final StaticModifier<CelestialLight> celestiallight = MODIFIERS.register("celestiallight", CelestialLight::new);
    public static final StaticModifier<Archangelwings> archangelwings = MODIFIERS.register("archangelwings", Archangelwings::new);
    public static final StaticModifier<GoldSimulate> gold_simulate = MODIFIERS.register("gold_simulate", GoldSimulate::new);
    public static final StaticModifier<EndSlayer> end_slayer = MODIFIERS.register("end_slayer", EndSlayer::new);
    public static final StaticModifier<StellarBlade> stellar_blade = MODIFIERS.register("stellar_blade", StellarBlade::new);
    public static final StaticModifier<All> all = MODIFIERS.register("all", All::new);
    public static final StaticModifier<StressModifier> stress = MODIFIERS.register("stress", StressModifier::new);
    public static final StaticModifier<fieryCapable> fiery_capable = MODIFIERS.register("fiery_capable", fieryCapable::new);
    public static final StaticModifier<Improve> improve = MODIFIERS.register("improve", Improve::new);
    public static final StaticModifier<Hardcore> hardcore = MODIFIERS.register("hardcore", Hardcore::new);
    public static final StaticModifier<Mutation> mutation = MODIFIERS.register("mutation", Mutation::new);
    public static final StaticModifier<ScorchInduced> scorch_induced = MODIFIERS.register("scorch_induced", ScorchInduced::new);
    public static final StaticModifier<FrozenInduced> frozen_induced = MODIFIERS.register("frozen_induced", FrozenInduced::new);
    public static final StaticModifier<IonizeIndused> ionize_induced = MODIFIERS.register("ionize_induced", IonizeIndused::new);
    public static final StaticModifier<PressureIndused> pressure_induced = MODIFIERS.register("pressure_induced", PressureIndused::new);
    public static final StaticModifier<Disorder> disorder = MODIFIERS.register("disorder", Disorder::new);
    public static final StaticModifier<StellarBlessing> stellar_blessing = MODIFIERS.register("stellar_blessing", StellarBlessing::new);
    public static final StaticModifier<DragonsWifu> dragons_wifu = MODIFIERS.register("dragons_wifu", DragonsWifu::new);
    public static final StaticModifier<ArmorDragonsWifu> armor_dragons_wifu = MODIFIERS.register("armor_dragons_wifu", ArmorDragonsWifu::new);
    public static final StaticModifier<TrinityCurse> trinitycurse = MODIFIERS.register("trinitycurse", TrinityCurse::new);
    public static final StaticModifier<TrinityBlessing> trinityblessing = MODIFIERS.register("trinityblessing", TrinityBlessing::new);
    public static final StaticModifier<Breeding> breeding = MODIFIERS.register("breeding", Breeding::new);
    public static final StaticModifier<Eros> eros = MODIFIERS.register("eros", Eros::new);
    public static final StaticModifier<ararar> ararar = MODIFIERS.register("ararar", ararar::new);
    public static final StaticModifier<NerfedDash> nerfed_dash = MODIFIERS.register("nerfed_dash", NerfedDash::new);
    public static final StaticModifier<Emp> emp = MODIFIERS.register("emp", Emp::new);
    public static final StaticModifier<Transmigration> transmigration = MODIFIERS.register("transmigration", Transmigration::new);
    public static final StaticModifier<Eventually> eventually = MODIFIERS.register("eventually", Eventually::new);
    public static final StaticModifier<Trauma> trauma = MODIFIERS.register("trauma", Trauma::new);
    public static final StaticModifier<Arrogance> ARROGANCE_STATIC_MODIFIER = MODIFIERS.register("arrogance", Arrogance::new);
    public static final StaticModifier<NerfColossal> nerf_colossal = MODIFIERS.register("nerf_colossal", NerfColossal::new);
    public static final StaticModifier<SharpBlade> SHARP_BLADE_STATIC_MODIFIER = MODIFIERS.register("sharpblade", SharpBlade::new);
    public static final StaticModifier<Cosmopolitan> COSMOPOLITAN_STATIC_MODIFIER = MODIFIERS.register("cosmopolitan", Cosmopolitan::new);
    public static final StaticModifier<Infinity> INFINITY_STATIC_MODIFIER = MODIFIERS.register("infinity", Infinity::new);
    public static final StaticModifier<DeepAndDeep> DEEP_AND_DEEP_STATIC_MODIFIER = MODIFIERS.register("deepanddeep", DeepAndDeep::new);
    public static final StaticModifier<DeepOceanEcho> DeepOceanEcho = MODIFIERS.register("deepoceanecho", DeepOceanEcho::new);
    public static final StaticModifier<Decoying> DECOYING_STATIC_MODIFIER = MODIFIERS.register("decoying", Decoying::new);
    public static final StaticModifier<DominateModifier> DOMINATE_MODIFIER_REPLACEMENT = MODIFIERS.register("dominate_replace", DominateModifier::new);
    public static final StaticModifier<LebegusProtection> LebegusProtection = MODIFIERS.register("lebegusprotection", LebegusProtection::new);
    public static final StaticModifier<RoxyLightning> RoxyLightning = MODIFIERS.register("roxylightning", RoxyLightning::new);
    public static final StaticModifier<Abelisures> Abelisures = MODIFIERS.register("abelisures", Abelisures::new);
    public static final StaticModifier<AlienMatter> AlienMatter = MODIFIERS.register("alienmatter", AlienMatter::new);
    public static final StaticModifier<ChewEvolution> chewevolution = MODIFIERS.register("chewevolution", ChewEvolution::new);
    public static final StaticModifier<OverwriteSoulDevouring> OVERWRITE_SOUL_DEVOURING_STATIC_MODIFIER = MODIFIERS.register("overwritesouldevouring", OverwriteSoulDevouring::new);
    public static final StaticModifier<PressureLoaded> pressure_loaded = MODIFIERS.register("pressure_loaded", PressureLoaded::new);
    public static final StaticModifier<FixedOracular> fixed_oracular = MODIFIERS.register("fixed_oracular", FixedOracular::new);
    public static final StaticModifier<OverwriteKnightGlory> OverwriteKnightGlory = MODIFIERS.register("knightglory", OverwriteKnightGlory::new);
    public static final StaticModifier<FixedPurify> fixed_purify = MODIFIERS.register("fixed_purify", FixedPurify::new);
    public static final StaticModifier<Flying> Flying = MODIFIERS.register("flying", Flying::new);
    public static final StaticModifier<CombustorModifier> combustor_modifier = MODIFIERS.register("combustor_modifier", CombustorModifier::new);
    public static final StaticModifier<NerfIgneous> igneous = MODIFIERS.register("igneous", NerfIgneous::new);
    public static final StaticModifier<Reflect> reflectStaticModifier = MODIFIERS.register("reflect", Reflect::new);
    public static final StaticModifier<EggBoost> egg_boost = MODIFIERS.register("egg_boost", EggBoost::new);
    public static final StaticModifier<FixedEarthCoreCrush> earth_core_crush = MODIFIERS.register("earth_core_crush", FixedEarthCoreCrush::new);
    public static final StaticModifier<AntiStunGoggles> anti_stun_goggles = MODIFIERS.register("anti_stun_goggles", AntiStunGoggles::new);
    public static final StaticModifier<DoubleEdged> double_edged = MODIFIERS.register("double_edged", DoubleEdged::new);
    public static final StaticModifier<Encrypt> encryptStaticModifier = MODIFIERS.register("encrypt", Encrypt::new);
    public static final StaticModifier<FixSanguine> fixSanguineStaticModifier = MODIFIERS.register("fixsanguine", FixSanguine::new);
    public static final StaticModifier<CrippleSupperMass> crippleSupperMassStaticModifier = MODIFIERS.register("cripplesuppermass", CrippleSupperMass::new);
    public static final StaticModifier<Ragnarok> ragnarok = MODIFIERS.register("ragnarok", Ragnarok::new);
    public static final StaticModifier<StarFury> STAR_FURY = MODIFIERS.register("star_fury", StarFury::new);
    public static final StaticModifier<PlasmaShielding> plasma_shielding = MODIFIERS.register("plasma_shielding", PlasmaShielding::new);
    public static final StaticModifier<OuterSpace> outer_space = MODIFIERS.register("outer_space", OuterSpace::new);
    public static final StaticModifier<CommonGobberBless> commonGobberBlessStaticModifier = MODIFIERS.register("commongobberbless", CommonGobberBless::new);
    public static final StaticModifier<NetherGobberBless> netherGobberBlessStaticModifier = MODIFIERS.register("nethergobberbless", NetherGobberBless::new);
    public static final StaticModifier<EnderGobberBless> enderGobberBlessStaticModifier = MODIFIERS.register("endergobberbless", EnderGobberBless::new);
    public static final StaticModifier<Refined> refined = MODIFIERS.register("refined", Refined::new);
    public static final StaticModifier<imprison> imprison = MODIFIERS.register("imprison", imprison::new);
    public static final StaticModifier<ArcaneOmniscient> magicomniscient = MODIFIERS.register("arcaneomniscient", ArcaneOmniscient::new);
    public static final StaticModifier<ArcaneProtect> magicProtectStaticModifier = MODIFIERS.register("arcaneprotect", ArcaneProtect::new);
    public static final StaticModifier<ArcaneTough> magictough = MODIFIERS.register("arcanetough", ArcaneTough::new);
    public static final StaticModifier<ArcaneFilling> arcanefilling = MODIFIERS.register("arcanefilling", ArcaneFilling::new);
    public static final StaticModifier<BloodGodBless> bloodgodbless = MODIFIERS.register("bloodgodbless", BloodGodBless::new);
    public static final StaticModifier<BloodThirsty> bloodthirsty = MODIFIERS.register("bloodthirsty", BloodThirsty::new);
    public static final StaticModifier<Subspace> subspace = MODIFIERS.register("subspace", Subspace::new);
    public static final StaticModifier<OriginBasedComputation> originbasedcomputation = MODIFIERS.register("originbasedcomputation", OriginBasedComputation::new);
    public static final StaticModifier<KingdomOfNumbers> kingdomofnumbers = MODIFIERS.register("kingdomofnumbers", KingdomOfNumbers::new);
    public static final StaticModifier<CurveMapping> curvemapping = MODIFIERS.register("curvemapping", CurveMapping::new);
    public static final StaticModifier<SupplementaryFormula> supplementaryformula = MODIFIERS.register("supplementaryformula", SupplementaryFormula::new);
    public static final StaticModifier<TriangleTheory> triangletheory = MODIFIERS.register("triangletheory", TriangleTheory::new);
    public static final StaticModifier<BuriedOcean> korea = MODIFIERS.register("buriedocean", BuriedOcean::new);
    public static final StaticModifier<ExplosionPrevent> ExplosionPrevent = MODIFIERS.register("explosionprevent", ExplosionPrevent::new);
    public static final StaticModifier<AtrophyBlade> AtrophyBlade = MODIFIERS.register("atrophyblade", AtrophyBlade::new);
    public static final StaticModifier<KillPhantom> KillPhantom = MODIFIERS.register("killphantom", KillPhantom::new);
    public static final StaticModifier<Qcf> qcfStaticModifier = MODIFIERS.register("qcf", Qcf::new);
    public static final StaticModifier<DoNotSplit> doNotSplitStaticModifier = MODIFIERS.register("donotsplit", DoNotSplit::new);
    public static final StaticModifier<AutoShooting> AUTO_SHOOTING = MODIFIERS.register("auto_shooting", AutoShooting::new);
    public static final StaticModifier<Fragment> Fragment = MODIFIERS.register("fragment", Fragment::new);
    public static final StaticModifier<Wearproof> wearproofStaticModifier = MODIFIERS.register("wearproof", Wearproof::new);
    public static final StaticModifier<Atheric> ATHERIC = MODIFIERS.register("atheric", Atheric::new);
    public static final StaticModifier<AmbrosiumPowered> AMBROSIUM_POWERED = MODIFIERS.register("ambrosium_powered", AmbrosiumPowered::new);
    public static final StaticModifier<StellarArrow> STELLAR_ARROW = MODIFIERS.register("stellar_arrow", StellarArrow::new);
    public static final StaticModifier<GravityShield> GRAVITY_SHIELD = MODIFIERS.register("gravity_shield", GravityShield::new);
    public static final StaticModifier<SecondaryArmor> SECONDARY_ARMOR = MODIFIERS.register("secondary_armor", SecondaryArmor::new);
    public static final StaticModifier<SentriteDefense> SENTRITE_DEFENSE = MODIFIERS.register("sentrite_defense", SentriteDefense::new);
    public static final StaticModifier<ValkyrieBless> VALKYRIE_BLESS = MODIFIERS.register("valkyrie_bless", ValkyrieBless::new);
    public static final StaticModifier<Reborn> REBORN = MODIFIERS.register("reborn", Reborn::new);
    public static final StaticModifier<LifeSteal> LIFE_STEAL = MODIFIERS.register("life_steal", LifeSteal::new);
    public static final StaticModifier<LifeEnhance> LIFE_ENHANCE = MODIFIERS.register("life_enhance", LifeEnhance::new);
    public static final StaticModifier<Phoenix> PHOENIX = MODIFIERS.register("phoenix", Phoenix::new);
    public static final StaticModifier<FixedArmorOracular> ARMOR_ORACLE = MODIFIERS.register("armor_oracle", FixedArmorOracular::new);
    public static final StaticModifier<SugarMaker> sugarmaker = MODIFIERS.register("sugarmaker", SugarMaker::new);
    public static final StaticModifier<HealthBoost> healthBoostStaticModifier = MODIFIERS.register("healthboost", HealthBoost::new);
    public static final StaticModifier<ShanXiPickaxe> shanXiPickaxeStaticModifier = MODIFIERS.register("shanxipickaxe", ShanXiPickaxe::new);
    public static final StaticModifier<SuperCritHit> superCritHitStaticModifier = MODIFIERS.register("supercrithit", SuperCritHit::new);
    public static final StaticModifier<Eternity> ETERNITY = MODIFIERS.register("eternity", Eternity::new);
    public static final StaticModifier<DevourerOfDragons> DEVOURER_OF_DRAGONS = MODIFIERS.register("devourer_of_dragons", DevourerOfDragons::new);
    public static final StaticModifier<DevourerOfDragonsArmor> DEVOURER_OF_DRAGONS_ARMOR = MODIFIERS.register("devourer_of_dragons_armor", DevourerOfDragonsArmor::new);
    public static final StaticModifier<PermafrostRevival> PERMAFROST_REVIVAL = MODIFIERS.register("permafrost_revival", PermafrostRevival::new);
    public static final StaticModifier<FieryJavelinModifier> FIERY_JAVELIN = MODIFIERS.register("fiery_javelin", FieryJavelinModifier::new);
    public static final StaticModifier<PlasmaWaveSlashEx> PLASMA_WAVE_SLASH = MODIFIERS.register("plasma_wave_slash", PlasmaWaveSlashEx::new);
    public static final StaticModifier<RegaliumModifier> REGALIUM = MODIFIERS.register("regalium", RegaliumModifier::new);
    public static final StaticModifier<MemoryAlloy> MEMORY_ALLOY = MODIFIERS.register("memory_alloy", MemoryAlloy::new);
    public static final StaticModifier<SunStrikeModifier> SUN_STRIKE = MODIFIERS.register("sunstrike", SunStrikeModifier::new);
    public static final StaticModifier<Industrial> INDUSTRIAL = MODIFIERS.register("industrial", Industrial::new);
    public static final StaticModifier<IndustrialArmor> INDUSTRIAL_ARMOR = MODIFIERS.register("industrial_armor", IndustrialArmor::new);
    public static final StaticModifier<organiccr> CARCINOGENIC = MODIFIERS.register("carcinogenic", organiccr::new);
    public static final StaticModifier<SecondaryArmorPlus> PIERCING_IMMUNE = MODIFIERS.register("piercing_immune", SecondaryArmorPlus::new);
    public static final StaticModifier<inorganiccr> PERMANENT_SCAR = MODIFIERS.register("permanent_scar", inorganiccr::new);
    public static final StaticModifier<NeutronCollect> NEUTRON_COLLECT = MODIFIERS.register("neutron_collect", NeutronCollect::new);
    public static final StaticModifier<StableStep> STABLE_STEP = MODIFIERS.register("stable_step", StableStep::new);
    public static final StaticModifier<LightStep> LIGHT_STEP = MODIFIERS.register("light_step", LightStep::new);
    public static final StaticModifier<Strengthen> STRENGTHEN = MODIFIERS.register("strengthen", Strengthen::new);
    public static final StaticModifier<Clean> CLEAN = MODIFIERS.register("clean", Clean::new);
    public static final StaticModifier<FixedPrecision> FIXED_PRECISION = MODIFIERS.register("fixed_precision", FixedPrecision::new);
    public static final StaticModifier<AntiCurse> ANTI_CURSE = MODIFIERS.register("anti_curse", AntiCurse::new);
    public static final StaticModifier<OxygeliumBudHelmet> OXGELIUM_BUG_HELMET = MODIFIERS.register("oxygelium_bud_helmet", OxygeliumBudHelmet::new);
    public static final StaticModifier<Sacrifice> SACRIFICE_MODIFIER = MODIFIERS.register("sacrifice", Sacrifice::new);
    public static final StaticModifier<BuffedAnger> ANGER = MODIFIERS.register("buffed_anger", BuffedAnger::new);
    public static final StaticModifier<ReworkedOmnipotent> OMNIPOTENT = MODIFIERS.register("omnipotent", ReworkedOmnipotent::new);
    public static final StaticModifier<StarDargonHit> STAR_DARGON_HIT_STATIC_MODIFIER = MODIFIERS.register("stardragonhit", StarDargonHit::new);
    public static final StaticModifier<IonApocalypse> ION_APOCALYPSE = MODIFIERS.register("ion_apocalypse", IonApocalypse::new);
    public static final StaticModifier<StarBless> starBlessStaticModifier = MODIFIERS.register("starbless", StarBless::new);
    public static final StaticModifier<CursedArrowModifier> CURSED_ARROW = MODIFIERS.register("cursed_arrow", CursedArrowModifier::new);
    public static final StaticModifier<NeutronCollectPlus> NEUTRON_COLLECT_PLUS = MODIFIERS.register("neutron_collect_plus", NeutronCollectPlus::new);
    public static final StaticModifier<SelfRegulate> SELF_REGULATE = MODIFIERS.register("self_regulate", SelfRegulate::new);
    public static final StaticModifier<Anisotropy> ANISOTROPY = MODIFIERS.register("anisotropy", Anisotropy::new);
    public static final StaticModifier<FixVoidTouch> VOID_TOUCH = MODIFIERS.register("void_touch", FixVoidTouch::new);
    public static final StaticModifier<CrystallizingArmor> CRYSTALLIZING_ARMOR = MODIFIERS.register("crystallizing_armor", CrystallizingArmor::new);
}
